export const NAVIGATION_DRAWER_WAS_TOGGLED = 'NAVIGATION_DRAWER_WAS_TOGGLED';


export const ATTEMPT_FETCH_HEROES = 'HERO_SEARCH/ATTEMPT_FETCH_HEROES';
export const HEROES_FETCHING_SUCCEEDED = 'HERO_SEARCH/HERO_FETCHING_SUCCEEDED';
export const HEROES_FETCHING_FAILED = 'HERO_SEARCH/HERO_FETCHING_FAILED';
export const HERO_NAME_TYPED = 'HERO_SEARCH/HERO_NAME_TYPED';
export const HERO_NAME_REMOVED = 'HERO_SEARCH/HERO_NAME_REMOVED';
export const HERO_SUGGESTION_SELECTED = 'HERO_SEARCH/HERO_SUGGESTION_SELECTED';
export const HERO_SELECTED = 'HERO_SEARCH/HERO_SELECTED';
export const REMOVE_SELECTED_HERO = 'HERO_SEARCH/REMOVE_SELECTED_HERO';

export const TAB_CHANGED = 'HERO_DETAIL/TAB_CHANGED';
export const ATTEMPT_FETCH_HERO = 'HERO_DETAIL/ATTEMPT_FETCH_HERO';
export const HERO_FETCHING_SUCCEEDED = 'HERO_DETAIL/HERO_FETCHING_SUCCEEDED';
export const HERO_FETCHING_FAILED = 'HERO_DETAIL/HERO_FETCHING_FAILED';

export const ATTEMPT_FETCH_HERO_COMICS = 'HERO_DETAIL/ATTEMPT_FETCH_HERO_COMICS';
export const HERO_COMICS_FETCHING_SUCCEEDED = 'HERO_DETAIL/HERO_COMICS_FETCHING_SUCCEEDED';
export const HERO_COMICS_FETCHING_FAILED = 'HERO_DETAIL/HERO_COMICS_FETCHING_FAILED';

export const ATTEMPT_FETCH_HERO_SERIES = 'HERO_DETAIL/ATTEMPT_FETCH_HERO_SERIES';
export const HERO_SERIES_FETCHING_SUCCEEDED = 'HERO_DETAIL/HERO_SERIES_FETCHING_SUCCEEDED';
export const HERO_SERIES_FETCHING_FAILED = 'HERO_DETAIL/HERO_SERIES_FETCHING_FAILED';

export const ATTEMPT_FETCH_HERO_STORIES = 'HERO_DETAIL/ATTEMPT_FETCH_HERO_STORIES';
export const HERO_STORIES_FETCHING_SUCCEEDED = 'HERO_DETAIL/HERO_STORIES_FETCHING_SUCCEEDED';
export const HERO_STORIES_FETCHING_FAILED = 'HERO_DETAIL/HERO_STORIES_FETCHING_FAILED';

export const ATTEMPT_FETCH_HERO_EVENTS = 'HERO_DETAIL/ATTEMPT_FETCH_HERO_EVENTS';
export const HERO_EVENTS_FETCHING_SUCCEEDED = 'HERO_DETAIL/HERO_EVENTS_FETCHING_SUCCEEDED';
export const HERO_EVENTS_FETCHING_FAILED = 'HERO_DETAIL/HERO_EVENTS_FETCHING_FAILED';
